# -*- coding: utf-8 -*-
"""Clientq2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1LNYjqZyMb4RZNOJxi2eE5dEoYMlZTz
"""

import socket

def check_vowel(a):
    vowels = 'aeiouAEIOU'
    for char in a:
        if char in vowels:
            return 1
    return 0

def reverse_string(string):
     return string[::-1]

def get_words(string):
    start = 0
    end = len(string) -1
    words = []
    for i in range(0, len(string),1):
        if string[i] == ' ':
            words.append(string[start:i])
            start = i+1
    words.append(string[start:end + 1])
    return words

while True:
    tcp_socket = socket.create_connection(('localhost', 1000))


    try:
        id = input("Enter message: ")
        data = str.encode(id)
        tcp_socket.sendall(data)

        amount_received = 0
        amount_expected = len(id)
        while amount_received < amount_expected:
            data = tcp_socket.recv(50)
            amount_received += len(data)
            print("Received data: "+ data.decode())
            break
        stringdata = data.decode()
        list = get_words(stringdata)
        for i in range(0,len(list),1):
            if check_vowel(list[i]) == 0:
                list[i] = reverse_string(list[i])
                message = ""
        for i in range(0,len(list),1):
            message = message + ' ' + list[i]

        print("After client processing: "+ message)

    finally:
        print("Closing socket")
        tcp_socket.close()



