# -*- coding: utf-8 -*-
"""Serverq2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6zUApiCe54O8FmE-0FTGvrhPUGc4jnQ
"""

import socket
import sys

def check_vowel(a):
    vowels = 'aeiouAEIOU'
    for char in a:
        if char in vowels:
            return 1
    return 0

def reverse_string(string):
     return string[::-1]

def get_words(string):
    start = 0
    end = len(string) -1
    words = []
    for i in range(0, len(string),1):
        if string[i] == ' ':
            words.append(string[start:i])
            start = i+1
    words.append(string[start:end + 1])
    return words

# Set up a TCP/IP server
tcp_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Bind the socket to server address and port 81
server_address = ('localhost', 1000)
tcp_socket.bind(server_address)


# Listen on port 81
tcp_socket.listen(1)

while True:
    print("Waiting for connection")
    connection, client = tcp_socket.accept()

    try:
        print("Connected to client IP: " + client[0])
        while True:
            # Receive and print data 32 bytes at a time, as long as the client is sending something
            data = connection.recv(32)
            if data:
                stringdata = data.decode('utf-8')
                print("Received data: "+ data.decode())
                if (check_vowel(stringdata) == 1):
                    list = get_words(stringdata)
                    for i in range(0,len(list),1):
                        if check_vowel(list[i]) == 1:
                            list[i] = reverse_string(list[i])
                    message = ""
                    for i in range(0,len(list),1):
                        message = message + ' ' + list[i]
                else:
                    message = stringdata
                connection.sendall(message.encode())
            else:
                print('No more data from client')
                break

    finally:
       connection.close()



