# -*- coding: utf-8 -*-
"""Clientq1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MD4xos0aBZYw0Vf8b95-hs3lkPU777R3
"""

import socket

# Create a connection to the server application on port 81

while True:
    tcp_socket = socket.create_connection(('localhost', 81))


    try:
        id = input("Enter client id: ")
        while (len(id) !=1):
            id = input("Client id is only one character. Enter client id: ")
        data = str.encode('Hello I am client and my id is ' + str(id))
        tcp_socket.sendall(data)

        amount_received = 0
        amount_expected = 50
        while amount_received < amount_expected:
            data = tcp_socket.recv(50)
            amount_received += len(data)
            print("Received data: "+ data.decode())
            break

    finally:
        print("Closing socket")
        tcp_socket.close()

